config/routes.rb
ShopOnline::Application.routes.draw do
  get "static_pages/home"

  get "static_pages/help"

  resources :carts
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :products
  resources :categories
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :orders
  resources :relationships, only: [:create, :destroy]
  resources :product_orders
  resources :manufacturers
  resources :product_microposts, only: [:create, :destroy]
  root to: 'products#index'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/napthe', to: 'users#napthe'
  match '/addpoint', to: 'users#addpoint'
  match '/nt', to: 'users#nt'

  match '/allproducts', to: 'products#index'
  match '/price_by_asc' , to: 'products#price_by_asc'
  match '/price_by_desc', to: 'products#price_by_desc'
  match '/newupdate',   to: 'products#newupdate'
  match '/comment',   to: 'products#comment'
  match '/mycarts', to: 'carts#mycarts', as: 'mycarts'
  match '/add_to_carts/:id', to:'carts#add_to_carts', as: 'add_to_carts', via: :post
  match '/delcart' , to: 'carts#destroy', via: :delete
  match '/newcategory', to: 'categories#new'
  match '/allcategory', to: 'categories#index'

  match '/new_manufacturer' ,  to:'manuafactorers#new'
  match '/home', to: 'static_pages#home'

end

app/models/product.rb
class Product < ActiveRecord::Base
  	attr_accessible :category_id, :description, :detail, :name, :price, :manufacturer_id
	belongs_to :category
	has_many :product_microposts, dependent: :destroy
	belongs_to :manufacturer
	has_many :orders, class_name: "Order", foreign_key: :product_id

	validates :name, presence: true
  	validates :category_id, presence: true
   	validates :price, presence: true
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

	def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])
    @product_microposts = @product.product_microposts.paginate(page: params[:page])
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    @categories = Category.all
    @manufacturers = Manufacturer.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
        @categories = Category.all
        @manufacturers = Manufacturer.all

  end

  # POST /products
  # POST /products.json
  def create

    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  def list_products
    @products = Product.find_all_by_category_id(params[:id])
    @category = Category.find(params[:id])
  

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  def price_by_asc
    @products = Product.find_by_sql("select * from products ORDER BY price ASC")

  end

  def price_by_desc
    @products = Product.find_by_sql("select * from products ORDER BY price DESC")
  end

  def newupdate
    @products = Product.find_by_sql("select * from products ORDER BY updated_at DESC")
  end
  def comment
    #@product = Product.find_by_id(params[:params].to_i)
    @product = Product.find_by_id(params[:id].to_i)
    content = params[:content]
    @product.product_microposts.create!(content: content)
    redirect_to product_path(@product)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for @product, :html => { :multipart => true } do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 <div id = "mainproduct" > 
    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name , :length => 5%>
    </div>
    <div class="field">
      <%= f.label :price %><br />
      <%= f.number_field :price %>
    </div>
    
    <div class="field">
      <%= f.label :category_id %><br />
      <%= f.collection_select :category_id,
      @categories, :id, :name %>
    </div>
    <div class="field">
      <%= f.label :manufacturer %><br />
      <%= f.collection_select :manufacturer_id,
      @manufacturers, :id, :name %>
    </div>
    

    <div class="field">
      <%= f.label :description %><br />
      <%= f.text_field :description %>
    </div>
  

    <div class="field">
     <%= f.label :detail %><br />
      <%= f.text_area :detail, :rows => 5, :cols => 30 %>
    </div>
  <div class="clr"></div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_formsort.html.erb
<MARQUEE> <span style="font-style:italic;">Thời gian làm việc từ 8h:30 đến 17h:50 các ngày trong tuần trừ chủ nhật.<a href="localhost:3000" target="_blank">iShop</a> </span></MARQUEE>
<br/>    
<div class="navbar-inner">
      <div id="fat-menu" class="dropdown">
              <ul><a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <t1>Sắp xếp theo giá</t1>
                 <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Giá từ thấp đến cao",price_by_asc_path %></li>
                <li class="divider"></li>
                <li><%= link_to "Giá từ cao xuống thấp",price_by_desc_path %></li>
                  </ul>
              <t1><%= link_to "Mới cập nhật",newupdate_path %></t1>
                  </ul>
      </div>
      <div>

      </div>
</div>


              
  

app/views/products/edit.html.erb
<%=render 'form' %>

app/views/products/index.html.erb
<%= render 'formsort'%>
<div style="margin-bottom:13px;">
  
<% @products.each do |product| %>
  <div class="item_id">
   <div class="title"><%= link_to product.name, product %></div>
    <div class="description"><%= product.description %></div>
    <div class="price">Price:&nbsp$<p2><%= product.price %></p2></div>
    <div class = "posted">
      <% if product.product_microposts.any? %>
      <p2><%= product.product_microposts.count %></p2> <b>comment<b>
      <%else%>
      <p2>0</p2><b>&nbspcomment</b>
      <%end%>
      </div>  
    <% if signed_in? %>
    <% if current_user.admin %>

    <div class="cart"><%= link_to 'Edit', edit_product_path(product) %></div>
    <div class="cart"><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></div>
    <% else %>
     <div class="cart"> <%= link_to 'Add to cart' ,  add_to_carts_path(product),class: "btn btn-medium btn-primary", method: "post",data: { confirm: 'Add to Your Cart?'}%></div>
    <% end %>
    <% end %>
    
 </div>
<% end %>

</div>

<br />
<% if signed_in? %>
<% if current_user.admin %>
<div style="clear:both;">
<%= link_to 'New Product', new_product_path,class: "btn btn-large btn-primary" %>
</div>
<% end %>
<% end %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/newupdate.html.erb
<%= render 'formsort'%>
<br/>
 <t2>Sản phẩm mới cập nhật</t2>. 
<div style="margin-bottom:13px;">  
<% @products.each do |product| %>
  <div class="item_id">
   <div class="title"><%= link_to product.name, product %></div>

    <div class="description"><%= product.description %></div>
    <div class="price">Price:&nbsp$<p2><%= product.price %></p2></div>
    <div class = "posted">
      <% if product.product_microposts.any? %>
      <p2><%= product.product_microposts.count %></p2> <b>comment<b>
      <%else%>
      <p2>0</p2><b>&nbspcomment</b>
      <%end%>
      </div>  
    <% if signed_in? %>
    <% if current_user.admin %>

    <div class="cart"><%= link_to 'Edit', edit_product_path(product) %></div>
    <div class="cart"><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></div>
    <% else %>
     <div class="cart"> <%= link_to 'Add to cart' ,  add_to_carts_path(product),class: "btn btn-medium btn-primary", method: "post", data: { confirm: 'Buy it?'} %></div>
    <% end %>
    <% end %>
    
 </div>
<% end %>

</div>

app/views/products/price_by_asc.html.erb
<%= render 'formsort'%>
<br/>
Danh sách sản phẩm theo mức giá <t1>tăng dần</t1>. 
<div style="margin-bottom:13px;">  
<% @products.each do |product| %>
  <div class="item_id">
   <div class="title"><%= link_to product.name, product %></div>

    <div class="description"><%= product.description %></div>
    <div class="price">Price:&nbsp$<p2><%= product.price %></p2></div>
    <div class = "posted">
      <% if product.product_microposts.any? %>
      <p2><%= product.product_microposts.count %></p2> <b>comment<b>
      <%else%>
      <p2>0</p2><b>&nbspcomment</b>
      <%end%>
      </div>  
    <% if signed_in? %>
    <% if current_user.admin %>

    <div class="cart"><%= link_to 'Edit', edit_product_path(product) %></div>
    <div class="cart"><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></div>
    <% else %>
     <div class="cart"> <%= link_to 'Add to cart' ,  add_to_carts_path(product),class: "btn btn-medium btn-primary", method: "post", data: { confirm: 'Buy it?'} %></div>
    <% end %>
    <% end %>
    
 </div>
<% end %>

</div>

app/views/products/price_by_desc.html.erb
<%= render 'formsort'%>
<br/>
Danh sách sản phẩm theo mức giá <t1>giảm dần</t1>. 
<div style="margin-bottom:13px;">  
<% @products.each do |product| %>
  <div class="item_id">
   <div class="title"><%= link_to product.name, product %></div>

    <div class="description"><%= product.description %></div>
    <div class="price">Price:&nbsp$<p2><%= product.price %></p2></div>
    <div class = "posted">
      <% if product.product_microposts.any? %>
      <p2><%= product.product_microposts.count %></p2> <b>comment<b>
      <%else%>
      <p2>0</p2><b>&nbspcomment</b>
      <%end%>
      </div>  
    <% if signed_in? %>
    <% if current_user.admin %>

    <div class="cart"><%= link_to 'Edit', edit_product_path(product) %></div>
    <div class="cart"><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></div>
    <% else %>
     <div class="cart"> <%= link_to 'Add to cart' ,  add_to_carts_path(product),class: "btn btn-medium btn-primary", method: "post", data: { confirm: 'Buy it?'} %></div>
    <% end %>
    <% end %>
    
 </div>
<% end %>

</div>

app/views/products/show.html.erb
<%= link_to 'Back', products_path %> 
<p id="notice"><%= notice %></p>

<table border = "1", width = "80%", align = "center">
  <tr height= "10px", align = "center", bgcolor = "#CCFF33">
    <td>Category</td>
    <td>Manufacturer</td>
    <td>Name Product</td>
    <td>Price</td>
    <td>Information</td>
  </tr>
  <tr align = center>
    <td><%= @product.category.name %></td>
    <td><%= @product.manufacturer.name%></td>
    <td><%= @product.name %></td>
    <td><%= @product.price %></td>
    <td><%= @product.detail %></td>
  </tr>
</table>
<% if signed_in? %>
<% if current_user.admin %>
<%= link_to 'Edit', edit_product_path(@product) %> |
<% end %>
<% end %>

</br>
<% if signed_in? %>
<div class="cart"> <%= link_to 'Add to cart' ,  add_to_carts_path(@product),class: "btn btn-small btn-primary", method: "post",data: { confirm: 'Add to Your Cart?'}%></div>
<%end%>
<!--Product micropost
Chon mot trong 2 cach deu duoc.cachh tren thi truyen ca params,cach duoi thi truyen moi id ,do vay xem lai controller ham comment-->

<div class="span8">
    <% if @product.product_microposts.any? %>
      <h3>(<%= @product.product_microposts.count %>) Comment</h3>
        <% @posts = @product.product_microposts.all %>
      <% @posts.each do |m|%>
      
        <div class="microposts">
          <p2><b><li>

          <li><span class="content">
            <%if signed_in?%>
            <%= @current_user.name%></li></b></p2>
            <%else%>
            <li>Unknow Member</li>
            <%end%>
            <%= m.content %></span>
              <span class="timestamp">
              Posted <%= time_ago_in_words(m.created_at) %> ago.
              </span>
          </li>
        </div>
      <% end %>
      <%else%>
      <h3>0 Comment</h3>
    <% end %>
  </div>
</div>

<%= form_for :products, url: {action: "comment"} do|f| %>
  <input type="textarea" rows="4" cols="20" name ="content" id = "content">
  <input type="hidden" name ="id" value = <%=@product.id %>>
  <%= f.submit "Make Comment"%>
  <%end%>