config/routes.rb
ShopOnline::Application.routes.draw do
  get "static_pages/home"

  get "static_pages/help"

  resources :carts
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :products
  resources :categories
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :orders
  resources :relationships, only: [:create, :destroy]
  resources :product_orders
  resources :manufacturers
  resources :product_microposts, only: [:create, :destroy]
  root to: 'products#index'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/napthe', to: 'users#napthe'
  match '/addpoint', to: 'users#addpoint'
  match '/nt', to: 'users#nt'

  match '/allproducts', to: 'products#index'
  match '/price_by_asc' , to: 'products#price_by_asc'
  match '/price_by_desc', to: 'products#price_by_desc'
  match '/newupdate',   to: 'products#newupdate'
  match '/comment',   to: 'products#comment'
  match '/mycarts', to: 'carts#mycarts', as: 'mycarts'
  match '/add_to_carts/:id', to:'carts#add_to_carts', as: 'add_to_carts', via: :post
  match '/delcart' , to: 'carts#destroy', via: :delete
  match '/newcategory', to: 'categories#new'
  match '/allcategory', to: 'categories#index'

  match '/new_manufacturer' ,  to:'manuafactorers#new'
  match '/home', to: 'static_pages#home'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://railstutorial.org/">Rails Tutorial</a>
    by Michael Hartl
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
      <li><%= link_to "admin",    '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">

      <%= link_to "iShop", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
              
          <% if signed_in? %>
          <% if checked_admin? %>
          <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Sản phẩm
                 <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Thêm mới', new_product_path %></li>
                <li><%= link_to "Xem tất cả", allproducts_path %></li>
                <li class="divider"></li>
              </ul>
            </li>

           <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Loại thiết bị
                 <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Thêm mới', newcategory_path %></li>
                <li><%= link_to "Xem tất cả", categories_path %></li>
              </ul>
          </li>

          <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Nhà sản xuất
                 <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Thêm mới', new_manufacturer_path %></li>
                <li><%= link_to "Xem tất cả", manufacturers_path %></li>
              </ul>
          </li>
            <li><%= link_to "Quản lý Thành Viên",users_path %></li>
            <li><%= link_to "Hóa đơn",orders_path %></li>
            <% else %>
             <li><%= link_to "Home",'#' %></li>
          <% end %>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <t1><%= current_user.name %></t1>
                 <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", '#' %></li>
                <li>Point: <p2><%= current_user.point%> Point</p2></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
            <li><%= link_to "Nạp thẻ",napthe_path %></li>
          <% else %>
            <li><%= link_to "Đăng nhập", signin_path %></li>
             <li><%= link_to "Đăng ký", signup_path %></li>
          <% end %>
          
          <li><%= link_to "Giỏ hàng",mycarts_path %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>


 

app/views/layouts/_leftpage.html.erb
1-----------------
1-----------------
1-----------------
1-----------------
1-----------------
1-----------------
1-----------------
1-----------------
1-----------------

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body >
	     <%= render 'layouts/header' %> 
          <div class="container">
             <% flash.each do |key, value| %>
                <div class="alert alert-<%= key %>"><%= value %></div>
             <% end %>
               <%= yield %>
               <div class="clr"></div>
        <%= render 'layouts/footer' %>
       <%= debug(params) if Rails.env.development? %>
      </div>
    </div>
	
</body>
</html>